Mite/Controllers/UserProfileController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Mite.BLL.Services;
using Mite.Core;
using Microsoft.AspNet.Identity;
using Mite.CodeData.Enums;
using System;
using System.Collections.Generic;
using Mite.Models;
using Mite.BLL.IdentityManagers;
using Mite.BLL.Infrastructure;

namespace Mite.Controllers
{
    public class UserProfileController : BaseController
    {
        private readonly IUserService userService;
        private readonly IPostsService postsService;
        private readonly IFollowersService followersService;
        private readonly IAuthorServiceService authorService;
        private readonly IProductsService productsService;
        private readonly ICharacterService characterService;
        private readonly AppUserManager userManager;
        private readonly ITariffService tariffService;

        public UserProfileController(IUserService userService, IPostsService postsService, IFollowersService followersService,
            IAuthorServiceService authorService, IProductsService productsService, ICharacterService characterService,
            AppUserManager userManager, ITariffService tariffService)
        {
            this.userService = userService;
            this.postsService = postsService;
            this.followersService = followersService;
            this.authorService = authorService;
            this.productsService = productsService;
            this.characterService = characterService;
            this.userManager = userManager;
            this.tariffService = tariffService;
        }
        /// <summary>
        /// Страница пользователя
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Index(string name)
        {
            var profile = await userService.GetUserProfileAsync(name, User.Identity.GetUserId());
            if (profile == null)
                return NotFound();

            return profile.IsAuthor ? View("Index", profile) : View("ClientIndex", profile);
        }
        /// <summary>
        /// Для мини-карточки пользователя
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public async Task<ActionResult> GetUserProfile(string name)
        {
            name = name.Replace(" ", string.Empty);
            var profile = await userService.GetUserProfileAsync(name, User.Identity.GetUserId());
            if (profile == null)
                return NotFound();
            //Обрезаем описание(всё для красоты)
            if(!string.IsNullOrEmpty(profile.About) && profile.About.Length > 50)
            {
                var about = profile.About;
                //Находим последний пробел, обрезаем до него
                about = about.Substring(0, 50);
                var lastSpace = about.LastIndexOf(' ');
                about = about.Substring(0, lastSpace);
                //Убираем последний символ, если это знак препинания
                var lastChar = about[about.Length - 1];
                if (lastChar == ',' || lastChar == '.' || lastChar == '-')
                {
                    about = about.Substring(0, about.Length - 1);
                }
                profile.About = about + "...";
            }
            return Json(JsonStatuses.Success, profile);
        }
        public ViewResult Notifications()
        {
            return View();
        }
        public Task<ActionResult> Followers(string name)
        {
            return Index(name);
        }
        [HttpPost]
        public async Task<ActionResult> Followers(string name, SortFilter sort)
        {
            var followers = await followersService.GetFollowersByUserAsync(name, sort);
            return Json(JsonStatuses.Success, followers);
        }
        public Task<ActionResult> Posts(string name)
        {
            return Index(name);
        }
        [HttpGet]
        public Task<ActionResult> Services(string name)
        {
            return Index(name);
        }
        [HttpPost]
        public async Task<ActionResult> Posts(string name, SortFilter sort, PostTypes? type)
        {
            IEnumerable<ProfilePostModel> posts;
            if (!string.Equals(name, User.Identity.Name, StringComparison.OrdinalIgnoreCase) && type == PostTypes.Drafts)
                return Forbidden();
            if (type == null)
                type = PostTypes.Published;
            posts = await postsService.GetByUserAsync(name, User.Identity.GetUserId(), sort, (PostTypes)type);
            return Json(JsonStatuses.Success, posts);
        }
        public Task<ActionResult> Followings(string name)
        {
            return Index(name);
        }
        public Task<ActionResult> Favorites(string name)
        {
            return Index(name);
        }
        public Task<ActionResult> Characters(string name)
        {
            return Index(name);
        }
        [HttpPost]
        public async Task<ActionResult> Followings(string name, SortFilter sort)
        {
            var followings = await followersService.GetFollowingsByUserAsync(name, sort);
            return Json(JsonStatuses.Success, followings);
        }
        [HttpPost]
        public async Task<ActionResult> Services(string name, SortFilter sort)
        {
            try
            {
                var services = await authorService.GetByUserAsync(name, sort);
                return Json(JsonStatuses.Success, services);
            }
            catch (DataServiceException e)
            {
                return Json(JsonStatuses.ValidationError, "Внутренняя ошибка");
            }
        }
        [HttpPost]
        public async Task<ActionResult> Favorites(string name, SortFilter sort)
        {
            try
            {
                var posts = await postsService.GetByUserAsync(name, CurrentUserId, sort, PostTypes.Favorite);
                return Json(JsonStatuses.Success, posts);
            }
            catch (DataServiceException e)
            {
                return Json(JsonStatuses.ValidationError, "Внутренняя ошибка");
            }
        }
        [HttpGet]
        public Task<ActionResult> Sponsors(string name)
        {
            return Index(name);
        }
        [HttpPost]
        public async Task<ActionResult> Sponsors(string name, SortFilter sort)
        {
            var user = await userManager.FindByNameAsync(name);
            if (user == null)
                return NotFound();
            var sponsors = await tariffService.GetSponsorsAsync(user.Id, sort);
            return Json(JsonStatuses.Success, sponsors);
        }
        [HttpGet]
        public Task<ActionResult> Products(string name)
        {
            return Index(name);
        }
        [HttpPost]
        public async Task<ActionResult> Products(string name, SortFilter sort)
        {
            try
            {
                var products = await productsService.GetForUserAsync(name, sort, CurrentUserId);
                return Json(JsonStatuses.Success, products);
            }
            catch(Exception)
            {
                return Json(JsonStatuses.ValidationError, "Внутренняя ошибка");
            }
        }
    }
}

Mite/Views/UserProfile/ClientIndex.cshtml
@using Mite.Helpers
@using Mite.CodeData.Enums
@model Mite.Models.ProfileModel

@{
    ViewBag.Title = "Профиль " + Model.UserName;
    var pageUserName = Model.UserName.ToLower();
    var currentUserName = User.Identity.Name.ToLower();
    var isMobileDevice = ViewHelper.IsMobileDevice(Request);
}
@section styles{
    <style>
        .center.aligned.statistics{
            justify-content: center;
        }
        .ui.tab.grid{
            height: auto;
            margin-top: 0;
            margin: -1rem;
        }
        p.about{
            font-size: 1.1em;
        }
    </style>
}
<div class="ui stackable grid">
    <div class="center aligned three wide column">
        <div class="ui segment">
            <img src="@Model.AvatarSrc" class="ui centered tiny circular image" width="80" height="80" />
            <h2 class="ui header">@Model.UserName</h2>
            <div class="ui center aligned small statistics">
                <div class="statistic">
                    <div class="value">@Model.Reliability</div>
                    <div class="label">Надежность</div>
                </div>
                <div class="small statistic">
                    <div class="value">@Model.FollowingsCount</div>
                    <div class="label">@ViewHelper.GetWordCase(Model.FollowingsCount, "Подписка", "Подписки", "Подписок")</div>
                </div>
            </div>
            <div class="ui divider"></div>
            <p class="about">@Model.About</p>
            @if (Model.ExternalLinks != null && Model.ExternalLinks.Count() > 0)
            {
                foreach (var link in Model.ExternalLinks)
                {
                    <a href="@link" class="link">
                        <i class="@link.IconClass icon"></i>
                        @link.ShowUrl
                    </a><br />
                }
            }
        </div>
    </div>
    <div class="thirteen wide column">
        <div class="ui stackable tabs menu" role="tablist">
            <a class="active item" role="tab" data-tab="followings">Подписки</a>
            <a class="item" role="tab" data-tab="favorites">Избранное</a>
            <div class="right item">
                <i class="filter icon"></i>
                Сначала&nbsp;
                <div class="ui inline dropdown" id="sortDropDown">
                    <div class="text">новые</div>
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <div class="active item" data-text="новые" data-value="@((byte)SortFilter.New)">Новые</div>
                        <div class="item" data-text="высший рейтинг" data-value="@((byte)SortFilter.Popular)">Высший рейтинг</div>
                        <div class="item" data-text="старые" data-value="@((byte)SortFilter.Old)">Старые</div>
                    </div>
                </div>
            </div>
        </div>
        @if (isMobileDevice)
        {
            <div class="ui loading active tab two column stackable grid" data-tab="followings"></div>
            <div class="ui tab two column stackable grid" data-tab="favorites"></div>
        }
        else
        {
            <div class="ui loading basic active tab three column stackable grid segment" data-tab="followings"></div>
            <div class="ui tab three column stackable grid" data-tab="favorites"></div>
        }
    </div>
</div>
@{ Html.RenderPartial("_ClientTemplates", Model); }
@section scripts{
    @Scripts.Render("~/bundles/grid", "~/bundles/jsrender")
    <script>
        var isOwner = @((currentUserName == pageUserName).ToString().ToLower());
        $(function () {
            var grids = [];
            $('.tab.grid[data-tab]').each(function (index, elem) {
                grids.push({
                    tabName: elem.dataset.tab,
                    elem: $(elem).masonry()
                });
            });
            var followingsTab = new Tab({
                parentTab: null,
                name: 'followings',
                isActive: true,
                tmplSelector: '#followersTmpl',
                emptyTmplSelector: '#emptyFollowingsTmpl'
            });
            var favoritesTab = new Tab({
                parentTab: null,
                name: 'favorites',
                isActive: false,
                tmplSelector: '#favoritePostsTmpl',
                emptyTmplSelector: '#emptyPostTmpl'
            });
            TabFilter.Tabs.items = [followingsTab, favoritesTab];
            TabFilter.Filters.add({
                name: 'sort',
                elem: $('#sortDropDown'),
                getVal: function () {
                    return this.elem.dropdown('get value') == ''
                        ? '@((byte)SortFilter.New)'
                        : this.elem.dropdown('get value');
                },
                updateState: function (newVal) {
                    this.elem.dropdown('set selected', newVal);
                }
            });
            TabFilter.init('@Url.Action("Index", "UserProfile", new { name = Model.UserName })', {
                beforeLoad: function(){
                    $('.active.tab').addClass('loading');
                },
                onSuccess: function(resp, tab){
                    var html;
                    if(resp.length == 0 && TabFilter.page == 1){
                        html = $(tab.emptyTmplSelector).html();
                        tab.content.html(html);
                    } else if(resp.length > 0) {
                        var tmpl = $.templates(tab.tmplSelector);
                        if (tab.name === 'favorites') {
                            resp.forEach(function (elem) {
                                elem.LastEdit += elem.LastEdit[elem.LastEdit - 1] == 'Z' ? '' : 'Z';
                                if (elem.PublishDate != null) {
                                    elem.PublishDate += elem.PublishDate[elem.PublishDate - 1] == 'Z' ? '' : 'Z';
                                    elem.PublicTimeStr = ViewHelper.getPastTense(new Date(elem.PublishDate).getTime());
                                } else {
                                    elem.PublicTimeStr = ViewHelper.getPastTense(new Date(elem.LastEdit).getTime());
                                }
                            });
                        }
                        html = tmpl.render(resp);

                        if(TabFilter.loadNextPage) {
                            tab.content.append(html);
                        } else{
                            tab.content.html(html);
                        }
                    }
                    $('.active.tab').removeClass('loading');
                    for(var i = 0; i < grids.length; i++){
                        if(tab.name == grids[i].tabName){
                            grids[i].elem.masonry('reloadItems');
                            grids[i].elem.imagesLoaded(function(){
                                grids[i].elem.masonry('layout');
                            }).progress(function(){
                                grids[i].elem.masonry('layout');
                            });
                            break;
                        }
                    }
                },
                onError: function () {
                    $('.active.tab').removeClass('loading');
                },
                ajax: {
                    type: 'post'
                }
            });
            $('#sortDropDown').dropdown({
                onChange: function () {
                    TabFilter.refresh();
                }
            });
        });
    </script>
}

Mite/Views/UserProfile/_ClientTemplates.cshtml
@using Microsoft.AspNet.Identity
@{ 
    var pageUserName = Model.UserName.ToLower();
    var currentUserName = User.Identity.Name.ToLower();
    var userId = User.Identity.GetUserId();
}
<script id="followersTmpl" type="text/x-jsrender">
    <div class="column">
        <div class="ui compact segment follower-card grid" style="margin: 0px;">
            <div class="five wide column">
                <img src="{{:AvatarSrc}}" class="ui small circular image">
            </div>
            <div class="ten wide column">
                <h4 class="ui header">
                    <span class="content">
                        <a href="/user/profile/{{:UserName}}">{{:UserName}}</a> &bull; <i class="yellow star icon"></i>{{:Rating}}
                        <span class="sub header">{{:Description}}</span>
                    </span>
                </h4>
            </div>
        </div>
    </div>
</script>
<script type="text/html" id="emptyFollowingsTmpl">
    <div class="column"></div>
    <div class="column">
        <h3 class="ui center aligned icon header" style="color: #6D6788">
            <i class="users icon"></i>
            @if (currentUserName == pageUserName)
            {
                <span class="content">
                    Вы пока ни на кого не подписались.
                </span>
            }
            else
            {
                <span class="content">
                    Пользователь пока ни на кого не подписался.
                </span>
            }
        </h3>
    </div>
</script>
<script id="favoritePostsTmpl" type="text/x-jsrender">
    <div class="column" data-post-id="{{:Id}}">
        <div class="ui segment {{if !IsImage && Cover != null}}invert{{/if}}{{if !ShowAdultContent}} hide-adult-content{{/if}} post-item"
             {{if !IsImage && Cover != null}} style="background: linear-gradient(rgba(181, 64, 198, 0.6),rgba(181, 64, 198, 0.5)), url({{:Cover}})" {{/if}}
             id="post{{:Id}}">
            @if (currentUserName == pageUserName)
            {
                <div class="extra content">
                    <button class="ui red floating compact button" onclick="FavoritePostsApi.remove(this, '{{:Id}}', '@userId', true)">Удалить</button>
                </div>
                <div class="ui {{if !IsImage && Cover != null}}inverted {{/if}} divider"></div>
            }
            {{if IsImage}}
            <div class="img-content">
                {{if IsPublished}}
                <a href="@Url.Action("ShowPost", "Posts")/{{:Id}}">
                    <img src="{{:Content}}" class="ui image" />
                </a>
                {{else}}
                <a href="/posts/edit/{{:Id}}">
                    <img src="{{:Content}}" class="ui image" />
                </a>
                {{/if}}
                {{if IsGif}}
                <div class="active gif-wrapper">
                    <button class="ui large primary circular icon button" onclick="loadFullGif('{{:FullPath}}', '{{:Id}}', $(this))"><i class="fire icon"></i></button>
                    <span class="ui violet label">gif</span>
                </div>
                {{/if}}
            </div>
            {{else}}
            <a class="post-content content" href="@Url.Action("ShowPost", "Posts")/{{:Id}}">
                {{:Content}}
            </a>
            {{/if}}
            <div class="ui {{if !IsImage && Cover != null}}inverted{{/if}} divider"></div>
            <div class="extra content">
                <a class="ui {{if !IsImage && Cover != null}}inverted {{/if}}header" style="margin-bottom: 5px" href="/posts/showpost/{{:Id}}">
                    {{:Header}}
                    <span class="sub header">
                        {{:Description}}
                    </span>
                </a>
                {{for Tags}}
                <a class="ui{{if !~root.IsImage && ~root.Cover != null}} invert{{/if}} label" href="/posts/top?tags={{>#data}}">{{>#data}}</a>
                {{/for}}
            </div>
            <div class="ui {{if !IsImage && Cover != null}}inverted{{/if}} divider"></div>
            <div class="extra content">
                {{:PublicTimeStr}}
                <div class="right">
                    <i class="yellow star icon"></i>{{:Rating}}
                    <i class="{{if Cover == null}}blue{{else}}black{{/if}} unhide icon"></i>{{:Views}}
                    <i class="green comments outline icon"></i>{{:CommentsCount}}
                </div>
            </div>
            {{if !ShowAdultContent}}
            <div class="ui center aligned dimmer">
                <div class="content">
                    <h2 class="ui inverted header">Взрослый контент(18+)</h2>
                    <button class="ui primary button" onclick="$(this).parents('.post-item').dimmer('hide')">Показать</button>
                </div>
            </div>
            {{/if}}
        </div>
    </div>
</script>
<script type="text/html" id="emptyPostTmpl">
    <div class="sixteen wide column">
        <h2 class="ui center aligned icon header" style="color: #6D6788; margin-top: 20px;">
            <i class="meh outline icon"></i>
            <span class="content">
                Работы не найдены.
            </span>
        </h2>
    </div>
</script>

Mite/Views/UserProfile/_Modals.cshtml
<div class="ui basic modal" id="confirmPostDelete">
    <div class="ui icon header">
        <i class="remove circle icon"></i>
        Удалить работу
    </div>
    <div class="content" style="text-align: center">
        <p>Вы уверены? Данное действие будет невозможно отменить</p>
    </div>
    <div class="actions">
        <div class="ui red basic cancel inverted button">
            <i class="remove icon"></i>
            Нет
        </div>
        <div class="ui green ok inverted button">
            <i class="checkmark icon"></i>
            Да
        </div>
    </div>
</div>