Mite/Controllers/CharacterController.cs
using Mite.BLL.Services;
using Mite.CodeData.Constants;
using Mite.Core;
using Mite.Models;
using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mite.Controllers
{
    [Authorize]
    public class CharacterController : BaseController
    {
        private readonly ICharacterService characterService;

        public CharacterController(ICharacterService characterService)
        {
            this.characterService = characterService;
        }
        public async Task<ActionResult> Add()
        {
            var model = new CharacterModel();
            if (User.IsInRole(RoleNames.Moderator))
                model.Universes = await characterService.GetUniversesAsync();
            return View("Edit", model);
        }
        public async Task<ActionResult> Edit(string id)
        {
            if(Guid.TryParse(id, out Guid gId))
            {
                var model = await characterService.GetAsync(gId);
                if (User.IsInRole(RoleNames.Moderator))
                    model.Universes = await characterService.GetUniversesAsync();
                if (model.UserId != CurrentUserId)
                    return Forbidden();
                return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<ActionResult> Add(CharacterModel model)
        {
            ValidateModel(model);
            if (!ModelState.IsValid)
                return Json(JsonStatuses.ValidationError, GetModelErrors());
            model.UserId = CurrentUserId;
            var result = await characterService.AddAsync(model);
            if(result.Succeeded)
                return Json(JsonStatuses.Success);
            return Json(JsonStatuses.ValidationError, result.Errors);
        }
        [HttpPost]
        public async Task<ActionResult> Update(CharacterModel model)
        {
            ValidateModel(model);
            if (!ModelState.IsValid)
                return Json(JsonStatuses.ValidationError, GetModelErrors());
            model.UserId = CurrentUserId;
            var result = await characterService.UpdateAsync(model);
            if(result.Succeeded)
                return Json(JsonStatuses.Success);
            return Json(JsonStatuses.ValidationError, result.Errors);
        }

        [Route("user/characters/{type?}")]
        public ActionResult UserCharacters()
        {
            var model = new UserCharactersModel();
            return View(model);
        }

        [HttpPost]
        [Route("user/characters/{type?}")]
        public async Task<ActionResult> Characters(CharacterTopFilterModel filterModel)
        {
            var characters = await characterService.GetByFilterAsync(CurrentUserId, filterModel);
            return Json(JsonStatuses.Success, characters);
        }

        public async Task<ActionResult> Show(string id)
        {
            if(Guid.TryParse(id, out Guid gId))
            {
                var character = await characterService.GetAsync(gId);
                if (character == null)
                    return NotFound();
                return View(character);
            }
            return NotFound();
        }

        private void ValidateModel(CharacterModel model)
        {
            if (Regex.IsMatch(model.Description, @"<\s*script\s*>"))
                ModelState.AddModelError("Description", "Присутствуют запрещенные теги");

            if (model.Features == null || model.Features.Count == 0)
                ModelState.AddModelError("Description", "Добавьте хотя бы одну особенность");
        }
    }
}

Mite/Controllers/UserCharactersController.cs
using Mite.BLL.Services;
using Mite.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mite.Controllers
{
    public class UserCharactersController : BaseController
    {
        private readonly ICharacterService characterService;

        public UserCharactersController(ICharacterService characterService)
        {
            this.characterService = characterService;
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Mite/Views/Character/Edit.cshtml
@using Mite.Extensions
@model Mite.Models.CharacterModel

@{
    ViewBag.Title = "Редактор персонажа";
    var saveUrl = Model.Id == null ? Url.Action("Add", "Character") : Url.Action("Update", "Character");
}
@section styles{
    <style>
        .feature-close.icon {
            cursor: pointer;
        }

        #editor {
            margin-top: 10px;
        }

        #externalImageSrc {
            margin-bottom: 10px;
        }
    </style>
}
<div class="ui segment">
    <h2 class="ui dividing header">@ViewBag.Title</h2>
    <div class="ui grid">
        <div class="two column row">
            <div class="center aligned column">
                <label class="ui dashed drop-zone segment" id="imgDropZone">
                    <span class="ui small blue header"><i class="cloud download icon"></i>Перетащите или нажмите</span>
                    <input type="file" id="imgFile" />
                </label>
                <div class="ui horizontal divider">Или</div>
                <div class="ui input">
                    <input type="text" id="externalImageSrc" placeholder="Ссылка на изображение" />
                </div>
                <button class="ui primary button" id="imageLinkPaste">Вставить</button>
                <div class="img-wrapper" id="img-wrapper">
                    @if (!string.IsNullOrEmpty(Model.ImageSrc))
                    {
                        <img src="@Model.ImageSrc" alt="@Model.Name" style="max-width: 100%" />
                    }
                </div>
                <div class="ui teal indicating progress" id="imgProgress">
                    <div class="bar">
                        <div class="progress"></div>
                    </div>
                </div>
            </div>
            <div class="column">
                <form class="ui char-form form">
                    @Html.HiddenFor(x => x.Id)
                    @Html.HiddenFor(x => x.ImageSrc)
                    @Html.EditorFor(x => x.Name, new { WithLabel = true })
                    @if (User.IsInRole(RoleNames.Moderator))
                    {
                        @Html.EditorFor(x => x.Original)
                        <div class="ui fluid search selection dropdown" id="select-universe">
                            <i class="dropdown icon"></i>
                            @Html.HiddenFor(x => x.Universe)
                            <div class="default text">Вселенная</div>
                            <div class="menu">
                                @if (Model.Universes != null && Model.Universes.Count > 0)
                                {
                                    foreach (var item in Model.Universes)
                                    {
                                        <div class="item" data-value="@item">@item</div>
                                    }
                                }
                            </div>
                        </div>
                    }
                    <div class="ui green m-success message">Персонаж успешно добавлен</div>
                    <div class="ui error message"></div>
                </form>
                @if (Model.Features != null && Model.Features.Count > 0)
                {
                    foreach (var feature in Model.Features)
                    {
                        Html.RenderPartial("_CharacterFeature", feature);
                    }
                }
                else
                {
                    Html.RenderPartial("_CharacterFeature", new Mite.Models.CharacterFeatureModel());
                }
                <button class="ui margined fluid green button" type="button" onclick="$(this).before($('#featureTmpl').html())" id="addFeatureBtn">
                    <i class="plus icon"></i>Добавить особенность
                </button>
                <button class="ui primary fluid button" type="button" id="saveBtn">Сохранить</button>
                
                <div class="ui blue icon message">
                    <i class="info icon"></i>
                    <div class="content">
                        <div class="header">Внимание!</div>
                        <p>Добавляйте персонажей, созданных Вами. Если необходим персонаж, созданный другим автором(из книги, кино и пр.), напишите об этом в один из чатов или в группу, и мы его добавим.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <div id="editor">
                @if (!string.IsNullOrEmpty(Model.Description))
                {
                    @Html.Raw(Model.Description);
                }
            </div>
        </div>
    </div>
</div>
<script type="text/html" id="featureTmpl">
    @{Html.RenderPartial("_CharacterFeature", new Mite.Models.CharacterFeatureModel());}
</script>
@*<script src="~/ckeditor5-build-classic/build/ckeditor.js"></script>
    <script src="~/ckeditor5-build-classic/build/translations/ru.js"></script>|*@
@*<link href="~/Content/DataEditing.css" rel="stylesheet" />*@
@Scripts.Render("~/bundles/editor", "~/bundles/api")
@Styles.Render("~/Content/editor")
<script>
    $('#Original').parent().checkbox();
    $('#imageLinkPaste').click(function () {
        var srcVal = $('#externalImageSrc').val();
        if (!/^https?:\/\//i.test(srcVal)) {
            iziToast.error({
                title: 'Упс!',
                message: 'Кажется, вы ввели неверную ссылку'
            });
            return;
        }
        $('#img-wrapper').html('<img src="' + srcVal + '" alt="@Model.Name" style="max-width: 100%" />');
        $('#ImageSrc').val(srcVal);
    });
    if ($('#select-universe').length) {
        $('#select-universe').dropdown({
            fullTextSearch: true,
            match: 'text',
            allowAdditions: true,
            keys: {
                delimiter: 13
            },
        });
    }
    ClassicEditor.create($('#editor')[0], {
        toolbar: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'imageUpload' , 'blockQuote', '|' ,'save'],
        language: 'ru',

        miteUpload: {
            uploadUrl: '@Url.Action("UploadDocImg", "Files", new { maxWidth = 1200 })'
        },
        save: {
            callback: function (data) {
                return CharacterMvc.save('@saveUrl', data, $('#saveBtn')[0]);
            }
        }
    }).then(function (editor) {
        $('#saveBtn').click(function () {
            CharacterMvc.save('@saveUrl', editor.getData(), this);
        });
    }).catch (function (error) {
        console.error(error);
    });
    var readSettings = {
        progress: $('#imgProgress'),
        field: $('#ImageSrc'),
        imgWrapper: $('#img-wrapper')
    };
    $('#imgFile').change(function (ev) {
        FileReaderHelper.inputDownloadHandler(ev, readSettings);
    });

    $('#imgDropZone').on('dragover', function (ev) {
        FileReaderHelper.dragOverHandler(ev);
    }).on('drop', function (ev) {
        FileReaderHelper.dropHandler(ev, readSettings);
    });

    @Html.Raw(Html.FormValidation(".char-form"))
    $('.char-item-form').form({
        fields: {
            FeatureDescription: {
                rules: [
                    {
                        type: 'empty',
                        prompt: 'Заполните описание'
                    },
                    {
                        type: 'maxLength[300]',
                        prompt: 'Слишком длинное описание'
                    }
                ]
            },
            FeatureName: {
                rules: [
                    {
                        type: 'empty',
                        prompt: 'Заполните название'
                    }
                ]
            }
        }
    });
</script>

Mite/Views/Character/Show.cshtml
@using Microsoft.AspNet.Identity
@model Mite.Models.CharacterModel

@{
    ViewBag.Title = Model.Name;
}
@section styles{
@Styles.Render("~/Content/editorcontent")
}
<div class="ui grid">
    <div class="twelve wide column">
        <div class="ui segment">
            <h2 class="ui dividing header">@Model.Name</h2>
            <div class="e-content">
                @Html.Raw(Model.Description)
            </div>
            <div class="ui fitted clearing hidden divider"></div>
        </div>
    </div>
    <div class="four wide column">
        <div class="ui basic segment" style="padding: 0">
            @if(Model.UserId == User.Identity.GetUserId())
            {
                @Html.ActionLink("Редактировать", "Edit", "Character", new { id = Model.Id }, new { @class = "ui inverted violet fluid button" })
            }
            <table class="ui collapsing celled table">
                <tbody>
                    <tr>
                        <td colspan="2">
                            <img src="@Model.ImageSrc" class="ui fluid image" />
                        </td>
                    </tr>
                    @foreach (var feature in Model.Features)
                    {
                        <tr>
                            <td>@feature.FeatureName</td>
                            <td>@feature.FeatureDescription</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Mite/Views/Character/UserCharacters.cshtml
@using Microsoft.AspNet.Identity
@model Mite.Models.UserCharactersModel
@{
    ViewBag.Title = "Персонажи";
    var currentUserId = User.Identity.GetUserId();
}
<div class="ui stackable grid">
    <div class="four wide column">
        <div class="ui vertical menu" id="userCharactersItems">
            <a class="active item" data-tab="all">Все</a>
            <a class="item" data-tab="own">Созданные мной</a>
            <div class="ui form item" id="originalFilter">
                @Html.EditorFor(x => x.OriginalType)
            </div>
        </div>
    </div>
    <div class="twelve wide column">
        <div class="ui segment">
            <h3 class="ui dividing header">Персонажи</h3>
            <div class="ui input">
                <input type="text" placeholder="Имя персонажа" id="characterSearch" 
                       onkeypress="if (event.keyCode == '13' || event.which == '13') TabFilter.refresh()" />
            </div>
            <button class="ui primary button" onclick="TabFilter.refresh()" title="Вы также можете нажать Enter для поиска">Найти</button>
            <div class="ui items tab" data-tab="all">
            </div>
            <div class="ui items tab" data-tab="own">
            </div>
            <div class="dot-loader-wrapper">
                <div class="dot-loader">
                    <div class="dot"></div>
                    <div class="dot"></div>
                    <div class="dot"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-jsrender" id="characterItemTmpl">
    <div class="item">
        <div class="image">
            <img src="{{:ImageSrc}}" />
        </div>
        <div class="content">
            <a class="header" href="/character/show/{{:Id}}">{{:Name}}</a>
            <div class="meta">
                {{if !User || User.Id == '@currentUserId'}}
                <a class="ui violet label" href="@Url.Action("Edit", "Character")/{{:Id}}">Редактировать</a>
                {{/if}}
                {{if Original}}
                <i class="blue user icon" title="Оригинальный персонаж"></i>
                {{/if}}
            </div>
            <div class="description">{{:Description}}</div>
            {{if User && User.Id != '@currentUserId'}}
            <div class="extra">
                <img src="{{:User.AvatarSrc}}" class="ui avatar image" />
                <a href="/user/profile/{{:User.UserName}}">{{:User.UserName}}</a>
            </div>
            {{/if}}
        </div>
    </div>
</script>
<script type="text/html" id="emptyCharacterTmpl">
    <h3 class="ui center aligned icon header" style="color: #6D6788; margin-top: 20px;">
        <i class="meh outline icon"></i>
        <span class="content">
            Персонажи не найдены.
        </span>
    </h3>
</script>
<script>
    var characterTmpl = $.templates('#characterItemTmpl');
    var characterItems = $('#characterItems');
    var tabItems = [];
    $('#originalFilter .checkbox').checkbox({
        onChange: function () {
            TabFilter.refresh();
        }
    });
    $('.item[data-tab]').each(function (index, el) {
        var $el = $(el);
        tabItems.push(new Tab({
            name: $el.data('tab'),
            isActive: $el.hasClass('active')
        }));
    });
    TabFilter.Tabs.items = tabItems;
    TabFilter.Filters.add({
        name: 'input',
        elem: $('#characterSearch'),
        getVal: function () {
            return this.elem.val();
        },
        updateState: function (newVal) {
            this.elem.val(newVal);
        }
    });
    TabFilter.Filters.add({
        name: 'originaltype',
        elem: $('#originalFilter .checkbox'),
        getVal: function () {
            var val = 0
            this.elem.each(function (index, rad) {
                var $rad = $(rad);
                if ($rad.checkbox('is checked')) {
                    val = $rad.children('input').val();
                }
            });
            return val;
        },
        updateState: function (newVal) {
            this.elem.each(function (index, rad) {
                if ($(rad).children('input').val() == newVal) {
                    $(rad).checkbox('set checked');
                }
            });
        }
    });
    TabFilter.init('/user/characters', {
        beforeLoad: function () {
            $('.dot-loader-wrapper').addClass('active');
        },
        onSuccess: function (resp, tab) {
            var html;
            if (resp.length == 0 && TabFilter.page == 1) {
                html = $('#emptyCharacterTmpl').html();
                tab.content.html(html);
            } else if (resp.length > 0) {
                html = characterTmpl.render(resp);

                if (TabFilter.loadNextPage) {
                    tab.content.append(html);
                } else {
                    tab.content.html(html);
                }
            }
            $('.dot-loader-wrapper').removeClass('active');
        },
        onError: function () {
            $('.dot-loader-wrapper').removeClass('active');
            iziToast.error({
                title: 'Упс...',
                message: 'Ошибка при загрузке работ'
            });
        },
        ajax: {
            type: 'post'
        }
    });
    Scrolling.init('.dot-loader-wrapper', function () {
        if (!TabFilter.loading) {
            var lastTab = TabFilter.Tabs.getLastActiveTab();
            TabFilter.loadNext();
        }
    });
</script>

Mite/Views/Character/_CharacterFeature.cshtml
@model Mite.Models.CharacterFeatureModel
        
<form class="ui char-item-form form">
    <div class="two fields">
        <div class="field">
            <label>@Html.DisplayNameFor(x => x.FeatureName)</label>
            <input type="text" name="@Html.NameFor(x => x.FeatureName)" placeholder="Дата рождения" value="@Model.FeatureName" />
        </div>
        <div class="field">
            <label>@Html.DisplayNameFor(x => x.FeatureDescription)</label>
            <textarea rows="2" name="@Html.NameFor(x => x.FeatureDescription)" placeholder="31 июля 1980 года">@Model.FeatureDescription</textarea>
        </div>
        <i class="red close feature-close icon" title="Удалить" onclick="$(this).parent().remove()"></i>
    </div>
    <div class="ui error message"></div>
</form>